# Generated by Django 4.1.2 on 2022-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogApp", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
